### ISSUE TITLE
SKA Simulation pipeline

### ISSUE THREAD

**Issue by cnwangfeng** [SKA-ScienceDataProcessor/algorithm-reference-library#47]
Hi Tim, 

I am running ska_simulate_arlexcute_pipeline.py.  Obviously, Line 107 has a bug. 

 zero_skymodel = SkyModel(images=zero_model) ->  zero_skymodel = SkyModel(image=zero_model)

However, even if I changed "images" to "image", the follow-up codes can't run successfully because gaintable is still "None" which would cause an error while invoking
    export_skymodel_to_hdf5(zero_skymodel, arl_path('%s/ska-pipeline_simulation_skymodel.hdf' % results_dir))

Best wishes

BTW: may I join ARL development team? It's so boring now because I have to manully sync ARL with my fork frequently. Meanwhile, it's hard to submit revisions. 

Feng

**Comment by timcornwell** [comment]
I’ll take a look.

Are you a member of the SKA Science Data Processor group on Github? If so, you should be have full access to ARL.

**Comment by cnwangfeng** [comment]
Hi Tim, 

Seemed not. I am a SDP MT member. Member of DALiuGe. Who is the admin of SDP  group? :-)

Feng

**Comment by timcornwell** [comment]
Ask Eugenia.

**Comment by timcornwell** [comment]
Hi Feng,

I’ve updated the master. There was a change in behaviour that I had not propagated to the scripts. The imaging functions used convert from block visibility to visibility when needed and the calibration functions used without conversion. Now it’s the other way around: the default assumption is visibility and the calibration routines convert to block visibility when needed.

I think you should be able to do git pull even if you are not a member of the SDP github. Have you tried that?

Tim

**Comment by cnwangfeng** [comment]
Hi Tim, 

Thanks a lot. Yes. I can pull even if I am not a member. But I should re-commit to my fork repository so as to guarantee their synchronization.

**Comment by cnwangfeng** [comment]
Thanks a lot. It can work now 

The only problem is the exit of the program which reported something error of tornado. 

(base) WF-MacBook-Pro:arl-1 wangfeng$ cd /Users/wangfeng/Dev/test/arl-1 ; env "PYTHONIOENCODING=UTF-8" "PYTHONUNBUFFERED=1" /Users/wangfeng/anaconda3/bin/python /Users/wangfeng/.vscode/extensions/ms-python.python-2019.1.0/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 63270 /Users/wangfeng/Dev/algorithm-reference-library/workflows/scripts/pipelines/ska-pipelines/ska_simulate_arlexecute_pipeline.py
Starting ska-pipelines simulation pipeline
<Client: scheduler='tcp://127.0.0.1:63285' processes=8 cores=8>
41 elements in vis_list
About to make visibility
{'vis': <data_models.memory_data_models.Visibility object at 0xbd2354748>, 'delA': 0.02, 'oversampling_synthesised_beam': 3.0, 'guard_band_image': 8.0, 'facets': 1, 'wprojection_planes': 91, 'max_wavelength': 2.99792458, 'min_wavelength': 2.99792458, 'maximum_baseline': 398.8338555988683, 'diameter': 35.0, 'primary_beam_fov': 0.085654988, 'image_fov': 0.685239904, 'facet_fov': 0.685239904, 'synthesized_beam': 0.002507309712959176, 'cellsize': 0.0008357699043197254, 'npixels': 820, 'npixels2': 1024, 'npixels23': 1024, 'w_sampling_image': 0.13557975095731223, 'w_sampling_facet': 0.13557975095731223, 'w_sampling_primary_beam': 8.677104061267983, 'time_sampling_image': 9.34903282646297, 'time_sampling_primary_beam': 598.3381008936301, 'freq_sampling_image': 10820.639845443251, 'freq_sampling_primary_beam': 692520.9501083681, 'wstep': 8.677104061267983, 'vis_slices': 91, 'nwpixels': 140}
About to make initial skymodel
Using w stack with 102 slices
About to run predict and corrupt to get corrupted visibility, and write files
tornado.application - ERROR - Exception in Future <Future cancelled> after timeout
Traceback (most recent call last):
  File "/Users/wangfeng/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 970, in error_callback
    future.result()
concurrent.futures._base.CancelledError
Terminated: 15
(base) WF-MacBook-Pro:arl-1 wangfeng$

**Comment by timcornwell** [comment]
That’s a Dask problem on closing. It has no effect on the results. 
Good!

**Comment by cnwangfeng** [comment]
Done.
